# Generated by Django 3.0.7 on 2020-07-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='update',
            new_name='updated',
        ),
    ]
